### ISSUE TITLE
Project export from classic to EMU is failing

### ISSUE THREAD

**Issue by ranjuvs-mphasis** [timrogers/gh-migrate-project#165]
![GitHub](https://github.com/timrogers/gh-migrate-project/assets/147516902/b2695dd4-72f9-4bb2-ab20-51890d4225e9)

Sub - Migrate project dashboard from GitHub Enterprise classic to GitHub EMU.
Issue - GraphQL is giving 500 Internal Server Error with fetch failed
Attached - Error SS

**Comment by timrogers** [comment]
Hi there! 👋 

A few questions:

1. Is the screenshot you shared the full output? I think there could be some lines missing at the bottom, as I would expect to see a response from the GraphQL queries. 

2. It is surprising that the GitHub API is returning 500 when you check your rate limit. That is quite unlikely to happen! Is there any chance that you have a proxy server in between you and GitHub?

**Comment by ranjuvs-mphasis** [comment]
> Hi there! 👋
> 
> A few questions:
> 
> 1. Is the screenshot you shared the full output? I think there could be some lines missing at the bottom, as I would expect to see a response from the GraphQL queries.
> 2. It is surprising that the GitHub API is returning 500 when you check your rate limit. That is quite unlikely to happen! Is there any chance that you have a proxy server in between you and GitHub?

1. missing lines
![GitHub_2](https://github.com/timrogers/gh-migrate-project/assets/147516902/0522892a-0a22-4093-82b2-2ad6d4412df6)

2. Yes we have Netskope proxy

**Comment by timrogers** [comment]
Are you specifying your proxy URL using the `--proxy-url` argument? From the "fetch failed" error, it looks like the tool is unable to connect to GitHub.com ( http://github.com/ ).

**Comment by ranjuvs-mphasis** [comment]
Thanks Time for the pointing out the issue. 

Including `--proxy-url` argument in the command fixed the issue.
